### ISSUE TITLE
Getting RenderCode(...) error

### ISSUE THREAD

**Issue by takirami** [seek-oss/playroom#59] opened 2019-04-15 11:38 UTC
Tried setting this up for a create-react-app build. `npm run playroom:start` compiles but all the frames give me the following error:

> RenderCode(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

Running the regular app with just a plain text component works just fine so I'm not suspecting an issue on that end.

This is my playroom.config.js
```
module.exports = {
    components: './src/components',
    outputPath: './dist/playroom',
  
    // Optional:
    title: 'My Awesome Library',
    widths: [320, 375, 768, 1024],
    port: 9000,
    openBrowser: true,
  };
```

Here is what I get.
![image](https://user-images.githubusercontent.com/1557849/56129702-80f2cf00-5f8b-11e9-85f0-66066a1f7de8.png)

I'm completely stuck on this. Any idea what might be causing this issue?

**Comment by michaeltaranto** [comment] 2019-04-15 22:40
Hmm, there's nothing wrong with the config, i would double check that all your components referenced in `src/components` are returning as intended. Also there is a marker (blue dot) next to the code pane which normally indicates a syntax error in the code pane, are you sure that pane is empty? Can you scroll up?

**Comment by takirami** [comment] 2019-04-16 06:41
Can't scroll up either. Inputing anything after the blue dot is resulting in the same error. 

![image](https://user-images.githubusercontent.com/1557849/56186995-f44b1e00-6029-11e9-9149-951ab5d358a6.png)

Here's my Test.js component (this renders correctly in the create-react app)
```
import React, { Component } from 'react';

class Text extends Component {
    render() {
        return (
            <div>
                Text
            </div>
        );
    }
}

export default Text;
```

and component.js

```
module.exports = {
    Text: require('./Components/Text/Text'),
    // etc...
  };
```
Changing any of these breaks the compiler so I'm assuming they're set up correctly?

**Comment by michaeltaranto** [comment] 2019-04-16 22:31
Not 100% sure what is going on there without being able to debug it. If you can provide a minimum reproducible example repo I can have a quick look.

I'll close this for now until we can confirm that this is not a configuration issue.

**Closed by michaeltaranto** 2019-04-16 22:31 UTC

**Comment by takirami** [comment] 2019-04-17 06:40
Here's my example code. All I've done is adde the Test component and the config.
https://github.com/takirami/playroom-demo

**Comment by michaeltaranto** [comment] 2019-04-17 11:43
Ah gotcha, yeah you havent configured playroom with any custom webpack config. Your code requires this to add support for the import/export usage in your component. For example everything works if you change `Test.js` to:
```diff
-import React, { Component } from 'react';
+const React = require('react');
+const { Component } = React;

class Test extends Component {
    render() {
        return (
            <div>
                This is only a test
            </div>
        );
    }
}

-export default Test;
+module.exports = Test;
```

**Comment by takirami** [comment] 2019-04-17 12:31
Okay, I was afraid it was something like this.
In that case I'm guessing this isn't really useful with create-react-app.
Thank you very much for clarifying.

**Comment by takirami** [comment] 2019-04-17 12:56
I really should learn to check before answering. 

Those changes didn't end up working for me. Just commenting in case someone else runs into the same issue.

**Comment by damianfabian** [comment] 2019-05-03 16:13
any solution about this? Any example with typeScript? Thanks!

**Comment by takirami** [comment] 2019-05-06 07:40
Finally got it working.

playroom.config.js needed this config
```
webpackConfig: () => ({
        module: {
          rules: [
            {
              test: /\.js$/,
              include: __dirname,
              exclude: /node_modules/,
              use: {
                loader: 'babel-loader',
                options: {
                  presets: ['@babel/preset-env', '@babel/preset-react']
                }
              }
            },
          ]
        }
      })

```

And the components.js needed to have `.default` added.
eg. 
```
module.exports = {
    Text: require('./Text').default,
    // etc...
  };
```
