### ISSUE TITLE
Crashes on chrome on iPad OS 14+

### ISSUE THREAD

**Issue by tamoore** [seek-oss/playroom#208] opened 2020-12-16 01:39 UTC
I was browsing the braid documentation today on my iPad Pro (so it should be able to computationally handle most things) and when I opened playroom from the documentation it crashed the website in incognito. See screenshot:

![0A365E0E-5F4C-44A3-BCCA-2DDD1B712ADC](https://user-images.githubusercontent.com/11851685/102293538-6dd3a600-3f9b-11eb-9b8b-8537b4ea26c5.png)

I tried it in normal mode (cookies enabled) and it was a bit better but for some reason the previews didn’t work:

![6D181783-0442-467B-BB8E-2EB62D6D1B8D](https://user-images.githubusercontent.com/11851685/102293626-952a7300-3f9b-11eb-8a70-5cdfa0bc9a58.png)

No extensions were enabled.

**Comment by michaeltaranto** [comment] 2020-12-16 02:30
Hey Todd 👋 

I have checked it out on Safari desktop and in the iOS simulator and cant replicate. My initial thought was local storage access in private mode, but doesnt seem to be breaking for me.

Noticed you're in Chrome, not Safari, any difference in Safari for you?

**Comment by michaeltaranto** [comment] 2020-12-16 02:32
Hey Todd 👋

I have checked it out on Safari desktop and in the iOS simulator and cant replicate. My initial thought was local storage access in private mode, but doesnt seem to be breaking for me, any difference in Safari for you?

**Comment by tamoore** [comment] 2020-12-16 03:16
It might just be my device then but it’s the same in safari:

![9263EC15-D50B-465D-89CB-DAD8E27A6AE4](https://user-images.githubusercontent.com/11851685/102300501-2c49f780-3fa9-11eb-86b8-a9d1f1af3285.png)

**Comment by michaeltaranto** [comment] 2020-12-16 03:34
To clarify, what do you mean by preview not working?

Might see if i can steal my wifes ipad to test it out on a real device 😄

**Comment by tamoore** [comment] 2020-12-16 03:41
I tried adding some components and it works on both chrome and safari, so
it was just the empty state that was confusing me.

It’s broken on incognito but that seems to be something you’d expect if it
saves a cookie of any sort.

Can close it you want, as it seems to work, probably user error. 😀

**Comment by michaeltaranto** [comment] 2020-12-16 03:47
Yeah there are preferences around themes, viewports and code that are stored in localStorage. So first thought was private browsing not being able to access storage, but that wouldn't be inconsistent, it would just flat out blow up if there was a problem.

All good, if you are happy that you cant reproduce reliably, let's close this.

**Closed by michaeltaranto** 2020-12-16 03:47 UTC
